/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./../src/components/animation.vue')['default']
    BindMobile: typeof import('./../src/components/member/bindMobile.vue')['default']
    BindQq: typeof import('./../src/components/member/bindQq.vue')['default']
    BindWechat: typeof import('./../src/components/member/bindWechat.vue')['default']
    BreadCrumbs: typeof import('./../src/components/BreadCrumbs.vue')['default']
    Captcha: typeof import('./../src/components/Captcha.vue')['default']
    ChangeInfo: typeof import('./../src/components/member/changeInfo.vue')['default']
    ChangePassword: typeof import('./../src/components/member/changePassword.vue')['default']
    Comment: typeof import('./../src/components/soft/comment.vue')['default']
    CommentItem: typeof import('./../src/components/soft/commentItem.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LkButton: typeof import('./../src/components/From/lk-button.vue')['default']
    LkInput: typeof import('./../src/components/From/lk-input.vue')['default']
    Logoff: typeof import('./../src/components/member/logoff.vue')['default']
    Markdown: typeof import('./../src/components/editor/markdown.vue')['default']
    MarkdownPreview: typeof import('./../src/components/markdownPreview.vue')['default']
    MBoard: typeof import('./../src/components/admin/MBoard.vue')['default']
    Notice: typeof import('./../src/components/admin/notice.vue')['default']
    Notification: typeof import('./../src/components/Notification.vue')['default']
    PostItem: typeof import('./../src/components/post/postItem.vue')['default']
    ReplyItem: typeof import('./../src/components/soft/replyItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../src/components/post/sideMenu.vue')['default']
    SoftItem: typeof import('./../src/components/soft/softItem.vue')['default']
    UpdateAvator: typeof import('./../src/components/member/updateAvator.vue')['default']
    UploadImage: typeof import('./../src/components/jizhu/uploadImage.vue')['default']
    WangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
  }
}
